# -*- coding: utf-8 -*-
import json, os

R = [
 ("simulado_nacional_enamed2025_q003", "D", "alta",
  "Quadro de desinibicao, comportamento social inadequado e anosognosia com MEEM 30/30 e perda funcional em paciente de 58 anos caracteriza demencia frontotemporal variante comportamental; a afasia primaria progressiva (variantes semantica e nao fluente) e um dos fenotipos do espectro da degeneracao lobar frontotemporal.",
  None),
 ("simulado_nacional_enamed2025_q008", "D", "alta",
  "Poliartralgia inflamatoria persistente com rigidez matinal apos 2 meses de chikungunya caracteriza a fase subaguda; o Manejo Clinico da Chikungunya (Ministerio da Saude) indica hidroxicloroquina 6 mg/kg/dia como droga de escolha nessa fase, e nao apenas analgesia simples.",
  None),
 ("simulado_nacional_enamed2025_q013", "C", "alta",
  "Ferimento transfixante da vesicula biliar com coleperitonio, em paciente estavel e sem outras lesoes, tem como tratamento definitivo a colecistectomia; rafia e colecistostomia mantem risco de fistula biliar e a drenagem de via biliar principal nao esta indicada sem lesao ductal.",
  None),
 ("simulado_nacional_enamed2025_q018", "B", "alta",
  "Nos protocolos de recuperacao acelerada (ACERTO/ERAS), liquidos claros - incluindo agua, cha sem leite e bebidas com maltodextrina - sao liberados ate 2 horas antes da inducao anestesica; refeicao leve exige 6 h e refeicao completa 8 h.",
  None),
 ("simulado_nacional_enamed2025_q023", "C", "alta",
  "NIC III confirmado por biopsia exige tratamento excisional; em mulher de 57 anos (pos-menopausa), com juncao escamocolunar nao visivel, a conduta e a exerese da zona de transformacao tipo 3 (conizacao), conforme Diretrizes Brasileiras/INCA.",
  None),
 ("simulado_nacional_enamed2025_q028", "A", "baixa",
  "Diante de IgG e IgM reagentes sem sorologia previa, a conduta padrao e iniciar espiramicina imediatamente e complementar a investigacao com teste de avidez de IgG; as demais alternativas propõem esquema triplice ou amniocentese sem confirmacao de infeccao fetal.",
  "Item ambiguo: com 18 semanas o teste de avidez ja perde valor discriminatorio (util ate ~16 semanas), o que torna a alternativa C (investigacao fetal) tambem defensavel; nenhuma alternativa reproduz integralmente o fluxograma do Ministerio da Saude."),
 ("simulado_nacional_enamed2025_q033", "C", "media",
  "Sintomas quase diarios, despertar noturno semanal e limitacao a atividade fisica configuram inicio de tratamento na etapa 3 do GINA para criancas de 6-11 anos: corticoide inalatorio em dose baixa associado a LABA, com SABA de resgate.",
  "A fronteira entre etapa 2 (CI dose baixa isolado) e etapa 3 pode gerar divergencia conforme a leitura da frequencia de sintomas."),
 ("simulado_nacional_enamed2025_q038", "A", "alta",
  "Episodio hipotonico-hiporresponsivo apos vacinacao aos 2 meses e classicamente atribuido ao componente pertussis de celulas inteiras (presente na penta/DTPw); a orientacao e completar o esquema com vacina acelular (DTPa).",
  None),
 ("simulado_nacional_enamed2025_q043", "E", "alta",
  "Trata-se de morte natural sem assistencia medica, sem sinais de violencia, em localidade que dispõe de Servico de Verificacao de Obito: o corpo deve ser encaminhado ao SVO, que emitira a declaracao de obito. O IML e reservado a mortes violentas ou suspeitas.",
  None),
 ("simulado_nacional_enamed2025_q048", "A", "alta",
  "VPP = verdadeiros positivos / total de testes positivos = 90/150 = 60%; a interpretacao correta e a proporcao de doentes entre os que testaram positivo (as alternativas com 90% descrevem sensibilidade).",
  None),

 ("enamed_simulado_2026_1_q003", "B", "alta",
  "Febre reumatica aguda com cardite moderada a grave (sopro mitral, cardiomegalia e congestao pulmonar) exige corticoterapia com prednisona, alem da erradicacao estreptococica com penicilina benzatina; AINE fica reservado a artrite sem cardite significativa.",
  None),
 ("enamed_simulado_2026_1_q008", "C", "alta",
  "Aumento escrotal cistico, indolor, com transiluminacao positiva e sem reducao a compressao corresponde a hidrocele nao comunicante do lactente, que regride espontaneamente na maioria dos casos; a conduta e observacao ate cerca de 1-2 anos antes de indicar cirurgia.",
  None),
 ("enamed_simulado_2026_1_q013", "A", "media",
  "Para lactente a termo, com peso adequado, a profilaxia recomendada pela SBP e pelo Programa Nacional de Suplementacao de Ferro e de 1 mg de ferro elementar/kg/dia, de forma continua, ate os 24 meses.",
  "As alternativas com 10-12,5 mg/dia remetem a recomendacao da OMS, o que pode gerar divergencia de gabarito conforme a fonte adotada como 'ultima recomendacao'."),
 ("enamed_simulado_2026_1_q018", "B", "alta",
  "Irritabilidade, olhos fundos, mucosas secas, sede intensa e prega cutanea que desaparece lentamente, com pulsos cheios, correspondem a 'desidratado' (dois ou mais sinais do plano B) no cartaz de manejo da diarreia do Ministerio da Saude.",
  None),
 ("enamed_simulado_2026_1_q023", "C", "alta",
  "Crise febril simples (generalizada, menos de 15 minutos, unica em 24 h, recuperacao completa, sem deficit) nao requer EEG, neuroimagem ou anticonvulsivante profilatico: a conduta e investigar e tratar o foco da febre.",
  None),
 ("enamed_simulado_2026_1_q028", "D", "alta",
  "Amilase e lipase acima de tres vezes o limite superior com dor tipica e colelitiase definem pancreatite aguda biliar; o tratamento inicial e clinico e, sendo quadro leve, a colecistectomia deve ser realizada na mesma internacao.",
  None),
 ("enamed_simulado_2026_1_q033", "A", "alta",
  "Adenocarcinoma gastrico localmente avancado com linfonodos regionais suspeitos e sem metastase a distancia: indica-se suporte nutricional, laparoscopia de estadiamento (para excluir carcinomatose oculta) e quimioterapia perioperatoria antes da gastrectomia. Linfonodo regional nao caracteriza doenca metastatica.",
  None),
 ("enamed_simulado_2026_1_q038", "C", "alta",
  "Incontaveis polipos em todo o colon e reto, com historia familiar de cancer colorretal precoce em dois parentes de primeiro grau, caracteriza polipose adenomatosa familiar, associada a mutacao germinativa do gene APC.",
  None),
 ("enamed_simulado_2026_1_q043", "A", "alta",
  "Hiperemia, dor, abaulamento e febre em topografia de hernioplastia com tela caracterizam infeccao de sitio cirurgico (com colecao/possivel infeccao de protese): a conduta e antibioticoterapia associada a exploracao cirurgica para drenagem e avaliacao da tela.",
  None),
 ("enamed_simulado_2026_1_q048", "C", "alta",
  "Resgate em ambiente fechado com perda de consciencia e escarro carbonaceo indica lesao inalatoria; a prioridade imediata (A do ATLS) e a intubacao orotraqueal precoce antes da instalacao do edema de via aerea. Reposicao volemica e escarotomia sao condutas subsequentes.",
  None),
 ("enamed_simulado_2026_1_q053", "A", "alta",
  "Fibrilacao atrial paroxistica recorrente sintomatica com FEVE de 38%: entre os antiarritmicos listados, apenas a amiodarona e segura na disfuncao sistolica; propafenona (classe IC) e contraindicada na cardiopatia estrutural, sotalol e proarritmico nesse contexto e adenosina nao mantem ritmo sinusal.",
  "O enunciado remete a um ECG nao disponivel, embora a resposta nao dependa dele."),
 ("enamed_simulado_2026_1_q058", "B", "alta",
  "Na DRC nao dialitica com hiperfosfatemia discreta, o KDIGO recomenda primeiro a restricao dietetica de fosfato (com atencao a aditivos), reservando quelantes para hiperfosfatemia progressiva ou persistente; quelantes de aluminio sao proscritos pelo risco de toxicidade.",
  None),
 ("enamed_simulado_2026_1_q063", "B", "alta",
  "Cefaleia subita, nauseas, vomitos e piora neurologica durante a infusao de alteplase indicam hemorragia intracraniana sintomatica: interromper imediatamente o trombolitico, realizar TC de cranio de urgencia e, confirmada a hemorragia, reverter com crioprecipitado/antifibrinolitico.",
  None),
 ("enamed_simulado_2026_1_q068", "B", "alta",
  "A terceira bulha e o achado de maior especificidade (cerca de 95-99%) para insuficiencia cardiaca, embora de baixa sensibilidade; edema, estertores e taquicardia sao inespecificos.",
  None),
 ("enamed_simulado_2026_1_q073", "A", "media",
  "Com hospital com hemodinamica a 30 minutos, o tempo porta-balao permanece dentro dos 120 minutos, de modo que a estrategia de escolha e a ICP primaria com transferencia imediata, apos dupla antiagregacao (AAS + inibidor de P2Y12) e anticoagulacao ainda na UPA.",
  "O eletrocardiograma citado no enunciado nao esta disponivel; a resposta depende de assumir supradesnivelamento de ST."),
 ("enamed_simulado_2026_1_q078", "D", "media",
  "Para parturiente de risco habitual em trabalho de parto ativo, a OMS e as Diretrizes Nacionais de Assistencia ao Parto Normal recomendam liberar a ingestao de liquidos e de dieta leve; o jejum de rotina nao reduz o risco de broncoaspiracao e aumenta o desconforto e a cetose.",
  None),
 ("enamed_simulado_2026_1_q083", "B", "alta",
  "A progesterona vaginal para prevencao de prematuridade recorrente e iniciada entre 16 e 24 semanas e nao ha beneficio em iniciar com 32 semanas; sem encurtamento cervical, cerclagem, tocoliticos profilaticos ou antibioticos nao estao indicados. Mantem-se vigilancia obstetrica.",
  None),
 ("enamed_simulado_2026_1_q088", "A", "media",
  "Testes previos nao reagentes com 8 semanas e VDRL 1:8 com 29 semanas caracterizam soroconversao, ou seja, sifilis recente (latente recente), cujo tratamento e penicilina G benzatina 2,4 milhoes UI em dose unica, inclusive na gestante; a parceria deve ser testada e tratada.",
  "A conduta com a parceria e imperfeita: o PCDT-IST recomenda tratamento presuntivo da parceria de gestante com sifilis independentemente do resultado dos testes, o que nao e contemplado por nenhuma alternativa com o esquema materno correto."),
 ("enamed_simulado_2026_1_q093", "B", "alta",
  "Corrimento amarelo-esverdeado bolhoso, pH acima de 4,5, teste das aminas positivo e colo com petequias ('colo em framboesa') definem tricomoniase, uma IST: trata-se a paciente (metronidazol 500 mg 12/12 h por 7 dias ou 2 g dose unica) e obrigatoriamente a parceria sexual, mesmo assintomatica. Tratamento topico e ineficaz.",
  None),
 ("enamed_simulado_2026_1_q098", "C", "media",
  "A violencia interpessoal e de notificacao compulsoria pelo profissional de saude que realizou o atendimento (ficha VIVA/SINAN), com finalidade epidemiologica e de protecao; notificar nao equivale a denunciar, preservando-se o sigilo e a autonomia da mulher adulta capaz, sem acionamento policial contra sua vontade.",
  "Ha tensao normativa com a Lei 13.931/2019, que preve comunicacao a autoridade policial em 24 h nos casos de violencia contra a mulher atendidos em servicos de saude, o que torna o item discutivel."),
]

path = "/home/user/meu-ccem-2026/adequacao-enamed/intermediario/consenso/rodada2_lote_03.json"
os.makedirs(os.path.dirname(path), exist_ok=True)
out = [{"id_origem": i, "resposta": r, "confianca": c, "motivo": m, "problema_do_item": p} for i, r, c, m, p in R]
with open(path, "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)
    f.write("\n")
print("ok", len(out))
